export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INACTIVE = 'USER_INACTIVE',

  // Workspace
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  WORKSPACE_SLUG_EXISTS = 'WORKSPACE_SLUG_EXISTS',
  NOT_WORKSPACE_MEMBER = 'NOT_WORKSPACE_MEMBER',
  ALREADY_WORKSPACE_MEMBER = 'ALREADY_WORKSPACE_MEMBER',
  CANNOT_REMOVE_OWNER = 'CANNOT_REMOVE_OWNER',
  INVALID_INVITE_TOKEN = 'INVALID_INVITE_TOKEN',

  // Project
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_KEY_EXISTS = 'PROJECT_KEY_EXISTS',

  // Task
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',

  // Comment
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  NOT_COMMENT_AUTHOR = 'NOT_COMMENT_AUTHOR',

  // Label
  LABEL_NOT_FOUND = 'LABEL_NOT_FOUND',
  LABEL_NAME_EXISTS = 'LABEL_NAME_EXISTS',

  // Channel
  CHANNEL_NOT_FOUND = 'CHANNEL_NOT_FOUND',
  NOT_CHANNEL_MEMBER = 'NOT_CHANNEL_MEMBER',
  CHANNEL_NAME_EXISTS = 'CHANNEL_NAME_EXISTS',

  // Message
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  NOT_MESSAGE_AUTHOR = 'NOT_MESSAGE_AUTHOR',

  // Attachment
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',

  // Notification
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // General
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
